### PR TITLE
Open modal with click anywhere on recipe card

### PR DESCRIPTION
**Pull request by terrifricker**
Previously, clicking anywhere within the "search-results" section except directly on a "View Recipe" button would show an empty modal.  (Tauri mentioned this on discord, too, noticing that clicking into the space where recipes should have shown up if none are found opened an empty modal.)

Solution:
- Check to see if a card was clicked
   - Add the check `if (e.target.id != "search-result)`
   - If true, a recipe card must have been clicked
   - If true, createModal
- Be able to get recipeId from any recipe card element clicked
   - Add an id containing the recipeId to the recipeObject and every html element within it
   - Each id is made of four letters, two representing the html element, plus "id", plus the recipeId
      - roid - recipe object id
      - imid - image id
      - tcid - title container id
      - raid - recipe title id
      - btid - button id
  - Get id using `e.target.id.slice(4)`

### CODE REVIEW

**Review by tauri-st — CHANGES_REQUESTED** [review]
I love this!! Makes it more accessible for people with mobility issues and just easy to use! Please just add to the CSS .recipe class "cursor: pointer" to make it obvious that the cards are clickable anywhere!

Even tho the card is clickable anywhere, I think we should still keep the buttons. Using a keyboard you can switch to landmarks, and the button is an automatically focusable landmark but the images and the whole card is only focusable with a mouse and it still is without adding unnecessary blabbing in the screen reader!

**Comment by terrifricker** [comment]
Made the change requested.  Add pointer cursor to recipe card.

**Review by chonger878 — APPROVED** [review]
Pointer cursor change acknowledged.

**Review by tauri-st — APPROVED** [review]
Poifect!

**Pull request merged**
